### PR TITLE
README.md: rephrased some of the content, added standard sections.

### PR DESCRIPTION
**Pull request by jeremiah**
Signed-off-by: Jeremiah C. Foster <jeremiah@jeremiahfoster.com>

I've rephrased some of the text under 'dual licensing' to make it more anodyne. Please let me know if this doesn't capture your intention Arwed.

### CODE REVIEW

**Comment by ArwedL** [comment]
I just wonder if the statement: "If you're interested in discussing licensing
+terms get in contact with us (ARichert@luxoft.com)." is strong enough so that interested parties understand that they could also have other licensing options? What about something like "We are open for discussion about different licensing schemas - just get in contact with us (ARichert@luxoft.com)"?

**Comment by jeremiah** [comment]
I've changed the README based on feedback -- would be great to get a review and a merge to this PR. Thanks!

**Review by ArwedL — APPROVED** [review]

**Comment by ArwedL** [comment]
Did it and already merged…

Thanks for your efforts and sorry for not being able to join last open source office appointment

Best regards,

Arwed Richert

**Comment by jeremiah** [comment]
Thanks @ArwedL!

**Pull request merged**
